# Minecraft Version - Default 1.19.4 (stable with Fabric)
minecraft_version=1.16.1

# Yarn Mappings version
yarn_mappings=1.16.1+build.1

# Fabric Loader version
loader_version=0.11.6

# Mod version
version=1.0.0

# REST API Configuration
api_port=8080
api_token=

# Enable/Disable Token Authentication (true/false)
api_auth_enabled=false
