#!/usr/bin/env python3
"""Generate docs/VERSIONS.md and the README version table.

Reads versions.json (the configured targets) and, when present,
build/distributions/manifest.json (what the build actually produced). A target
is only marked as building when the manifest lists an artifact for it.

Usage: python3 scripts/generate-version-table.py [--check]
       --check exits non-zero if the generated files are out of date.
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSIONS_JSON = ROOT / "versions.json"
MANIFEST = ROOT / "build" / "distributions" / "manifest.json"
VERSIONS_DOC = ROOT / "docs" / "VERSIONS.md"
README = ROOT / "README.md"

GENERATED_BANNER = "<!-- GENERATED FILE. DO NOT EDIT MANUALLY. Run: python3 scripts/generate-version-table.py -->"
README_START = "<!-- SUPPORTED_VERSIONS_START -->"
README_END = "<!-- SUPPORTED_VERSIONS_END -->"


def version_key(version):
    """Sort Minecraft versions semantically: 1.9 < 1.16.1 < 1.20.4."""
    parts = []
    for chunk in re.split(r"[.\-+]", version):
        parts.append((0, int(chunk)) if chunk.isdigit() else (1, chunk))
    return parts


def load_versions():
    data = json.loads(VERSIONS_JSON.read_text(encoding="utf-8"))
    return data["modVersion"], data["versions"]


def load_manifest():
    if not MANIFEST.is_file():
        return None
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def rows(versions, manifest):
    built = {}
    if manifest:
        for artifact in manifest.get("artifacts", []):
            built[artifact["minecraft"]] = artifact
    for key in sorted(versions, key=version_key):
        spec = versions[key]
        yield spec, built.get(spec["minecraft"])


def versions_doc(mod_version, versions, manifest):
    lines = [
        GENERATED_BANNER,
        "",
        "# Supported Minecraft versions",
        "",
        f"Command API `{mod_version}`. Every row below is a target configured in "
        "[`versions.json`](../versions.json) with a module under `versions/`.",
        "",
    ]
    if manifest:
        lines += [
            "The Build column reflects `build/distributions/manifest.json`, produced by "
            "`./gradlew buildAllVersions`.",
            "",
        ]
    else:
        lines += [
            "No build manifest was found, so no target can be reported as building. "
            "Run `./gradlew buildAllVersions` and regenerate this file.",
            "",
        ]

    lines += [
        "| Minecraft | Java | Fabric Loader | Fabric API | Build | Artifact |",
        "| --------- | ---: | ------------- | ---------- | ----- | -------- |",
    ]
    for spec, artifact in rows(versions, manifest):
        status = "✅" if artifact else "❌"
        name = f"`{artifact['file']}`" if artifact else "—"
        lines.append(
            f"| {spec['minecraft']} | {spec['java']} | {spec['loader']} | "
            f"{spec['fabricApi']} | {status} | {name} |"
        )

    lines += [
        "",
        "✅ means the artifact exists in the current build manifest. ❌ means the "
        "target is configured but produced no JAR in that build.",
        "",
        "## Building a single target",
        "",
        "```bash",
    ]
    for spec, _ in rows(versions, manifest):
        lines.append(f"./gradlew :{spec['module']}:build")
    lines += [
        "```",
        "",
        "See [ADDING_VERSION.md](ADDING_VERSION.md) to add a target and "
        "[BUILD.md](BUILD.md) for the build layout.",
        "",
    ]
    return "\n".join(lines)


def readme_block(mod_version, versions, manifest):
    lines = [
        README_START,
        "<!-- Generated by scripts/generate-version-table.py. Do not edit by hand. -->",
        "",
        "| Minecraft | Status | Download artifact |",
        "|---|---|---|",
    ]
    for spec, artifact in rows(versions, manifest):
        if artifact:
            lines.append(f"| {spec['minecraft']} | ✅ Build passing | `{artifact['file']}` |")
        else:
            expected = f"commandapi-{mod_version}+mc{spec['minecraft']}.jar"
            lines.append(f"| {spec['minecraft']} | ❌ Not built | `{expected}` (expected) |")
    lines += ["", README_END]
    return "\n".join(lines)


def replace_readme_block(text, block):
    if README_START not in text or README_END not in text:
        raise SystemExit(
            f"{README} is missing the {README_START} / {README_END} markers."
        )
    pattern = re.compile(
        re.escape(README_START) + ".*?" + re.escape(README_END), re.DOTALL
    )
    return pattern.sub(lambda _: block, text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail instead of writing when files are out of date")
    args = parser.parse_args()

    mod_version, versions = load_versions()
    manifest = load_manifest()

    outputs = {
        VERSIONS_DOC: versions_doc(mod_version, versions, manifest),
        README: replace_readme_block(
            README.read_text(encoding="utf-8"), readme_block(mod_version, versions, manifest)
        ),
    }

    stale = [p for p, content in outputs.items()
             if not p.is_file() or p.read_text(encoding="utf-8") != content]

    if args.check:
        for path in stale:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        if stale:
            print("Run: python3 scripts/generate-version-table.py", file=sys.stderr)
            return 1
        print("Generated version tables are up to date.")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    if not manifest:
        print(f"note: {MANIFEST.relative_to(ROOT)} not found; "
              "every target is reported as not built.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
